### ISSUE TITLE
Can you give me some advice？

### ISSUE THREAD

**Issue by CloudWise-Lukemiao** [raydac/mvn-golang-example#2]
I want to install the go environment through the mvn plugin, and then execute the command of go get -u http://xxx, is there any example for reference?

**Comment by raydac** [comment]
you could take a look at examples for the plugin, for [instance this one](https://github.com/raydac/mvn-golang/tree/master/mvn-golang-examples/mvn-golang-example-goterm)

**Comment by CloudWise-Lukemiao** [comment]
Why does it prompt that plugin cannot be found[image]

**Comment by CloudWise-Lukemiao** [comment]
> you could take a look at examples for the plugin, for [instance this one](https://github.com/raydac/mvn-golang/tree/master/mvn-golang-examples/mvn-golang-example-goterm)

hi,I want to execute the two commands "go mod tidy" and "MAGE - V". Can the plug-in support

**Comment by raydac** [comment]
for go mod tidy you can use
```xml
         <execution>
            <id>go-mod-tidy</id>
            <goals>
              <goal>mod</goal>
            </goals>
            <phase>initialize</phase>
            <configuration>
              <command>tidy</command>
            </configuration>
          </execution>
```
and what means MAGE -V I don't understand

**Comment by CloudWise-Lukemiao** [comment]
> for go mod tidy you can use
> 
> ```
>          <execution>
>             <id>go-mod-tidy</id>
>             <goals>
>               <goal>mod</goal>
>             </goals>
>             <phase>initialize</phase>
>             <configuration>
>               <command>tidy</command>
>             </configuration>
>           </execution>
> ```
> 
> and what means MAGE -V I don't understand

thanks
